blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask questions on Stack Overflow (preferred)
    url: https://stackoverflow.com/questions/tagged/vqgan-clip
    about: Ask structured and fully-formed questions about vqgan-clip.
